App\Domain\Product\Product:
  type: entity
  id:
    id:
      type: uuid

  fields:
    name:
      type: string
    description:
      type: text
    price:
      type: money

#  embedded:
#    price:
#      class: Money
