index:
  path: /greetings
  controller: App\UI\Http\GreetingHttpAdapter

get-products:
  path: /products
  methods: GET
  controller: App\UI\Http\GetProductsHttpAdapter

post-products:
  path: /products
  methods: POST
  controller: App\UI\Http\CreateProductHttpAdapter
