index:
    path: /greetings
    controller: App\UI\Http\GetGreetingHttpController

get-products:
    path: /products
    methods: GET
    controller: App\UI\Http\GetProductsHttpController

post-products:
    path: /products
    methods: POST
    controller: App\UI\Http\CreateProductHttpController
