index:
  path: /greetings
  controller: App\Controller\GreetingHttpController

get-products:
  path: /products
  methods: GET
  controller: App\Controller\GetProductsHttpController

post-products:
  path: /products
  methods: POST
  controller: App\Controller\CreateProductHttpController
